### ISSUE TITLE
yarn error

### ISSUE THREAD

**Issue by MaxCarritt** [inductiveautomation/ignition-sdk-examples#47]
Hi, trying to follow the instructions at https://github.com/inductiveautomation/ignition-sdk-examples/tree/master/perspective-component/web

I run yarn inside this directory and get the following error:

error Couldn't find package "@inductiveautomation/perspective-client@^1.0.3" required by "@myCompanyNamespace/example-client@1.0.0" on the "npm" registry.

**Comment by PerryAJ** [comment]
Issue reproduced and being investigated.  Did note that the version you report (1.0.3) is rather old, but either way, I did find the 1.0.3 package in the repository when I checked, so am looking into why it's not resolving. 

I intend to fix this and the reported gradle issue with a PR as soon as I sort out what is going on.  Thanks again for the reports!

**Comment by MaxCarritt** [comment]
Ah weird well I installed yarn for the first time today, strange it didn't grab the latest. I updated yarn and it worked.

**Comment by MaxCarritt** [comment]
So yarn did its thing, and the next step is to run "lerna run build" which i did from the web directory as well, here is the output:

`root@stu1:/home/max/ignition-sdk-examples/perspective-component/web# lerna run build
info cli using local version of lerna
lerna notice cli v3.13.1
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@myCompanyNamespace/example-client'
lerna ERR! yarn run build stdout:
yarn run v1.22.4
$ yarn run clean && yarn run lint && webpack --mode development
$ rimraf dist .awcache
$ tslint -p tsconfig.json -c tslint.json typescript/**/*.tsx typescript/**/*.ts -t stylish
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Failed to load /home/max/ignition-sdk-examples/perspective-component/web/packages/client/tslint.json: Invalid "extends" configuration value - could not require "tslint-react". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
error Command failed with exit code 1.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@myCompanyNamespace/example-client'
root@stu1:/home/max/ignition-sdk-examples/perspective-component/web# 
`

**Comment by PerryAJ** [comment]
Hi Max, 

Looks like that error is failing due to an issue with the tslint configuration.  You may remove the 'tslint-react' entry in the tslint configuration file and see if it helps.  Otherwise, I'm planning on getting a PR up to fix this as soon as I can.

**Comment by PerryAJ** [comment]
Submitted a PR that should resolve the build failures you reported @MaxCarritt .  Feel free to pull down that branch (https://github.com/PerryAJ/ignition-sdk-examples/tree/perspective-component-fixes) to give it a shot.  Otherwise, Let me know if you hit any further problems.  Thanks again for the report!

**Comment by MaxCarritt** [comment]
thanks, it looks like yarn worked for the web dir!

**Comment by MaxCarritt** [comment]
(the gradle build is still failing but as thats a different issue I'm going to assume you're still looking into that.) thanks for your quick responses and work!

**Comment by MaxCarritt** [comment]
Ah I got a successful gradle build,  I think what did it was removing the tslint-react' entry that you described

**Comment by MaxCarritt** [comment]
oh also, there was a bit that said something like  "UNlICENSED" and had to be changed to "UNLICENSED"
